name: ðŸš€ VPS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync to VPS via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: "tharitourtravel_maxfininsurance.com"
          REMOTE_PORT: "21" # <--- CHANGE THIS if your VPS uses a different port
          TARGET: "/home/maxfine/public_html/tharitourtravel.com/"
          SOURCE: "/"
          ARGS: "-rlgoDzvc -i --delete"
          EXCLUDE: "/.git/, /.github/, /node_modules/"