- name: ðŸ“‚ Sync to VPS via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
          TARGET: "/home/maxfine/public_html/tharitourtravel.com/"
          SOURCE: "/"
          ARGS: "-rlgoDzvc -i --delete"
          # Added the specific config files to the exclude list
          EXCLUDE: "/.git/, /.github/, /node_modules/, /app/Config/App.php, /app/Config/Database.php"